### ISSUE TITLE
tck-rewrite-ant: Persistence mapping-file (e.g. myMappingFile.xml) files are not added to deployments

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck-tools#140]
Getting a `mapping.xml resource not found` during deployment of ee.jakarta.tck.persistence.core.StoredProcedureQuery.Client1PmservletTest and other tests. 

```
2024-09-03 17:31:45,992 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 13) MSC000001: Failed to start service jboss.persistenceunit."jpa_core_StoredProcedureQuery_vehicles.ear#CTS-EM-NOTX".__FIRST_PHASE__: org.jboss.msc.service.StartException in service jboss.persistenceunit."jpa_core_StoredProcedureQuery_vehicles.ear#CTS-EM-NOTX".__FIRST_PHASE__: org.hibernate.boot.MappingException: Unable to resolve explicitly named mapping-file : myMappingFile.xml : origin(myMappingFile.xml)
        at org.jboss.as.jpa@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.service.PhaseOnePersistenceUnitServiceImpl$1$1.run(PhaseOnePersistenceUnitServiceImpl.java:113)
        at org.jboss.as.jpa@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.service.PhaseOnePersistenceUnitServiceImpl$1$1.run(PhaseOnePersistenceUnitServiceImpl.java:89)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at org.wildfly.security.elytron-base@2.5.0.Final//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:664)
        at org.jboss.as.jpa@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.service.PhaseOnePersistenceUnitServiceImpl$1.run(PhaseOnePersistenceUnitServiceImpl.java:122)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:840)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: org.hibernate.boot.MappingException: Unable to resolve explicitly named mapping-file : myMappingFile.xml : origin(myMappingFile.xml)
        at org.hibernate@6.4.10.Final//org.hibernate.boot.model.process.internal.ScanningCoordinator.applyScanResultsToManagedResources(ScanningCoordinator.java:214)
        at org.hibernate@6.4.10.Final//org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:81)
        at org.hibernate@6.4.10.Final//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:150)
        at org.hibernate@6.4.10.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:296)
        at org.hibernate@6.4.10.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:198)
        at org.hibernate@6.4.10.Final//org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:35)
        at org.hibernate@6.4.10.Final//org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:102)
        at org.hibernate.jipijapa-hibernate6@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.hibernate.TwoPhaseBootstrapImpl.<init>(TwoPhaseBootstrapImpl.java:27)
        at org.hibernate.jipijapa-hibernate6@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.hibernate.HibernatePersistenceProviderAdaptor.getBootstrap(HibernatePersistenceProviderAdaptor.java:220)
        at org.jboss.as.jpa@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.service.PhaseOnePersistenceUnitServiceImpl.createContainerEntityManagerFactoryBuilder(PhaseOnePersistenceUnitServiceImpl.java:239)
        at org.jboss.as.jpa@34.0.0.Beta1-SNAPSHOT//org.jboss.as.jpa.service.PhaseOnePersistenceUnitServiceImpl$1$1.run(PhaseOnePersistenceUnitServiceImpl.java:110)
        ... 10 more

```

List of TCK tests that have this under jpa folder in platform tck:

```
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/jpa/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/src/main/java/ee/jakarta/tck/persistence/jpa/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/src/main/resources/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/packaging/ejb/descriptor/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/packaging/jar/persistence.xml:        <mapping-file>myMappingFile2.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/jta/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile1.xml</mapping-file>
platform-tests/target/classes/ee/jakarta/tck/persistence/ee/pluggability/contracts/resource_local/persistence.xml:        <mapping-file>META-INF/myMappingFile2.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/java/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/src/main/resources/ee/jakarta/tck/persistence/se/descriptor/persistence.xml:        <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/StoredProcedureQuery/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/annotations/elementcollection/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>
spec-tests/target/classes/ee/jakarta/tck/persistence/core/entitytest/apitests/persistence.xml:    <mapping-file>myMappingFile.xml</mapping-file>

```

**Comment by scottmarlow** [comment]
tck10/jakartaeetck/dist/com/sun/ts/tests/jpa/core/StoredProcedureQuery contains jpa_core_StoredProcedureQuery_vehicles.ear that has lib/jpa_core_StoredProcedureQuery.jar that has myMappingFile.xml in the root (and META-INF/persistence.xml).

The contained persistence.xml references the mapping file:
```
<persistence xmlns="https://jakarta.ee/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence     https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd" version="3.0">
  <persistence-unit name="CTS-EM" transaction-type="JTA">
    <description>Persistence Unit for CTS Vehicle Tests</description>
    <jta-data-source>jdbc/DB1</jta-data-source>
    <mapping-file>myMappingFile.xml</mapping-file>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee2</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.EmployeeMappedSC</class>
  </persistence-unit>
  <persistence-unit name="CTS-EM2" transaction-type="JTA">
    <description>Persistence Unit for CTS Vehicle Tests</description>
    <jta-data-source>jdbc/DB1</jta-data-source>
    <mapping-file>myMappingFile.xml</mapping-file>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee2</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.EmployeeMappedSC</class>
  </persistence-unit>
  <persistence-unit name="CTS-EM-NOTX" transaction-type="RESOURCE_LOCAL">
    <description>The persistence.xml file may be used to designate
                  more than one persistence unit within the same scope.
                  Persistence Unit for Application Managed Resource Local</description>
    <non-jta-data-source>jdbc/DB_no_tx</non-jta-data-source>
    <mapping-file>myMappingFile.xml</mapping-file>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.Employee2</class>
    <class>com.sun.ts.tests.jpa.core.StoredProcedureQuery.EmployeeMappedSC</class>
  </persistence-unit>
</persistence>

```

**Comment by scottmarlow** [comment]
This looks to be a tck-rewrite-ant issue as the myMappingFile.xml is not added to the deployment.

**Comment by scottmarlow** [comment]
Details from https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#objectrelational-mapping-files:

> An object/relational mapping XML file contains mapping information for the classes it lists.
> - An object/relational mapping XML file named orm.xml may be located in the META-INF directory in the root of the persistence unit or in the META-INF directory of any jar file referenced by the persistence.xml.
> - Alternatively, or in addition, one or more mapping files may be referenced by the mapping-file elements of the persistence-unit element. These mapping files may be present anywhere on the class path.
> 

```
Example:

<persistence-unit name="OrderManagement2">
    <mapping-file>mappings.xml</mapping-file>
</persistence-unit>
```

**Comment by starksm64** [comment]
The resources were missing from the spec-tests jar.
