### ISSUE TITLE
sigtest plugin fails to run under Java SE 21

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck-tools#25]
The sigtest-maven-plugin tests expect that they can install a security manager to capture the exit code. Need to look into how to change this as it fails under SE 21 with exceptions like:

```
[ERROR] org.netbeans.apitest.StrictCheckSigtestTest.testOverrideFinalize -- Time elapsed: 0.010 s <<< ERROR!
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:429)
        at org.netbeans.apitest.ExecuteUtils.execute(ExecuteUtils.java:66)
        at org.netbeans.apitest.StrictCheckSigtestTest.checkAPIsEqual(StrictCheckSigtestTest.java:62)
        at org.netbeans.apitest.CheckNewSigtestTest.testOverrideFinalize(CheckNewSigtestTest.java:265)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at junit.framework.TestCase.runTest(TestCase.java:177)
        at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:79)
        at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:484)
        at org.netbeans.junit.NbTestCase$1Guard.run(NbTestCase.java:405)
        at org.netbeans.junit.NbTestCase.runBare(NbTestCase.java:505)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at org.netbeans.junit.NbTestCase.run(NbTestCase.java:294)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by starksm64** [comment]
It is also invoking ant via org.apache.tools.ant.Main.main to run the tests instead of just invoking the task directly. There is a comment about this in ExecuteUtils#execute(File, String[]), and this seems to be the reason for using the SecurityManager.
